name: Deploy EC2 Backup App

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Apply Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_db_username: ${{ secrets.DB_USER }}
          TF_VAR_db_password: ${{ secrets.DB_PASS }}
          TF_VAR_ami_id: ${{ secrets.AMI_ID }}
          TF_VAR_key_name: ${{ secrets.EC2_KEY_NAME }}
